### ISSUE TITLE
collectionFormat multi in /queries/array/multi/string/valid appears not match swagger2 definition

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/autorest.testserver#197]
There appears to be a divergence of swagger2 definition of "collectionFormat" and our codegen/testserver implementation.
 
swagger2 on collectionFormat
https://swagger.io/docs/specification/2-0/describing-parameters/

csv -> foo,bar,baz
multi -> foo=value&foo=another_value

So "multi" seems should be "foo=value&foo=another_value".

our testserver
https://github.com/Azure/autorest.testserver/blob/master/swagger/url-multi-collectionFormat.json#L86-L101
https://github.com/Azure/autorest.testserver/blob/master/legacy/routes/queries.js#L159-L162

It seems to be "csv" instead of "mult", which is "foo,bar,baz".

---

I've checked java and python generator implementation, both seems to be doing "csv" on "multi".

---

Checked the with appplatform service, they actually requires the multiple instance of query paramter.

Spec https://github.com/Azure/azure-rest-api-specs/blob/master/specification/appplatform/resource-manager/Microsoft.AppPlatform/preview/2019-05-01-preview/appplatform.json#L1745-L1756
expects to take in "version=v1&version=v2"

**Comment by lmazuel** [comment]
Step 1 : https://github.com/Azure/autorest.modelerfour/issues/314

**Comment by lmazuel** [comment]
Azure-core 1.8.0 + autorest 5.1.0.preview8
