### ISSUE TITLE
[QUERY] Whether header Location=somethingBadWhichShouldNotBeUsed is intended in some LRO tests

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/autorest.testserver#244]
Some LRO cases set `Location` header to `somethingBadWhichShouldNotBeUsed`. It causes failure on Java SDK, as azure-core-management tries to parse the URL and throw exception on this (which seems not an unreasonable result, as that URL is indeed invalid), even though SDK likely not going to use the URL because `Azure-AsyncOperation` would take precedence.

E.g.
https://github.com/Azure/autorest.testserver/blob/master/legacy/routes/lros.js#L240

Javadoc on URL
https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/net/URL.html#%3Cinit%3E(java.lang.String)
It throws checked exception `MalformedURLException` on constructor, regardless of whether the URL is used or not.

I would like to know whether this is intended, i.e., does these cases really intend to verify that SDK should never parse the `Location` header, or this is just a side-effect of the placeholder string.

If it is not intended, could we replace it with something looks like URL, e.g. http://somethingBadWhichShouldNotBeUsed

**Comment by lmazuel** [comment]
Hi @weidongxu-microsoft 
It's intended that you don't use use it at all, hence the string name :). Why would you parse this header in the first place, since you know you will go through the Azure-AsyncOperation header anyway?

**Comment by weidongxu-microsoft** [comment]
@lmazuel 

It is just code in our dependency lib azure-core-management. It parses (or just loads) both, then decide what to do with them.

You can close them if there is no change in testservice. It only affect a few cases. I could work on azure-core-management later.

**Comment by lmazuel** [comment]
Ok, let's close, I would prefer runtime to not try to pre-interpret something it will not use anyway.
